
# "//H023FILESRV01/OldPupilSHare/slamjam/messenger/defaultserver.json"

FILE_PATH = None  # "D:/messenger servers/defaultserver.db"

MESSAGE_AMOUNT_THRESHOLD = 20
MESSAGE_LENGTH_THRESHOLD = 100

UPDATE_FREQUENCY = 500

# Colours
BACKGROUND_COLOUR = "#4f545c"
DARK_BACKGROUND_COLOUR = "#36393f"
TEXTBOX_COLOUR = "#2f3136"
BUTTON_COLOUR = "#4e5d94"
BUTTON_ACTIVE_COLOUR = "#2e3757"
ERROR_COLOUR = "#f04747"
DARK_TEXT_COLOUR = "#72767d"

# Fonts
HEADING_FONT = ("Verdana", 14)
MEDIUM_FONT = ("Verdana", 10)
TEXTBOX_FONT = ("Verdana", 8)
